//1-2-англ раскладка(обычн, +shift)
//3-4-руск раскладка(обычн, +shift)

const KEYS = [
  {
    Backquote: ['`', '~', ']', '['],
    Digit1: ['1', '!'],
    Digit2: ['2', '@', '"'],
    Digit3: ['3', '#', '№'],
    Digit4: ['4', '$', '%'],
    Digit5: ['5', '%', ':'],
    Digit6: ['6', '^', ','],
    Digit7: ['7', '&', '.'],
    Digit8: ['8', '*', ';'],
    Digit9: ['9', '('],
    Digit0: ['0', ')'],
    Minus: ['-', '_'],
    Equal: ['=', '+'],
    Backspace: ['delete'],
  },
  {
    Tab: ['tab'],
    KeyQ: ['q', 'Q', 'й', 'Й'],
    KeyW: ['w', 'W', 'ц', 'Ц'],
    KeyE: ['e', 'E', 'у', 'У'],
    KeyR: ['r', 'R', 'к', 'К'],
    KeyT: ['t', 'T', 'е', 'Е'],
    KeyY: ['y', 'Y', 'н', 'Н'],
    KeyU: ['u', 'U', 'г', 'Г'],
    KeyI: ['i', 'I', 'ш', 'Ш'],
    KeyO: ['o', 'O', 'щ', 'Щ'],
    KeyP: ['p', 'P', 'з', 'З'],
    BracketLeft: ['[', '{', 'х', 'Х'],
    BracketRight: [']', '}', 'ъ', 'Ъ'],
    Backslash: ['\\', '|', 'ё', 'Ё'],
  },
  {
    CapsLock: ['capsLock'],
    KeyA: ['a', 'A', 'ф', 'Ф'],
    KeyS: ['s', 'S', 'ы', 'Ы'],
    KeyD: ['d', 'D', 'в', 'В'],
    KeyF: ['f', 'F', 'а', 'А'],
    KeyG: ['g', 'G', 'п', 'П'],
    KeyH: ['h', 'H', 'р', 'Р'],
    KeyJ: ['j', 'J', 'о', 'О'],
    KeyK: ['k', 'K', 'л', 'Л'],
    KeyL: ['l', 'L', 'д', 'Д'],
    Semicolon: [';', ':', 'ж', 'Ж'],
    Quote: ['\'', '"', 'э', 'Э'],
    Enter: ['return'],
  },
  {
    ShiftLeft: ['shift'],
    KeyZ: ['z', 'Z', 'я', 'Я'],
    KeyX: ['x', 'X', 'ч', 'Ч'],
    KeyC: ['c', 'C'],
    KeyV: ['v', 'V', 'м', 'М'],
    KeyB: ['b', 'B', 'и', 'И'],
    KeyN: ['n', 'N', 'т', 'Т'],
    KeyM: ['m', 'M', 'ь', 'Ь'],
    Comma: [',', '<', 'б', 'Б'],
    Period: ['.', '>', 'ю', 'Ю'],
    Slash: ['/', '?'],
    ArrowUp: ['&#9650;'],
    ShiftRight: ['shift'],
  },
  {
    ControlLeft: ['control'],
    AltLeft: ['option'],
    MetaLeft: ['command'],
    Space: [' '],
    MetaRight: ['command'],
    ArrowLeft: ['&#9668;'],
    ArrowDown: ['&#9660;'],
    ArrowRight: ['&#9658;'],
    AltRight: ['option'],
  },
];

export default KEYS;
