//1-2-англ раскладка(обычн, +shift)
//3-4-руск раскладка(обычн, +shift)

const KEYS = [
  {
    Backquote: ['`', '~'],
    Digit1: ['1', '!'],
    Digit2: ['2', '@'],
    Digit3: ['3', '№'],
    Digit4: ['4', '$'],
    Digit5: ['5', '%'],
    Digit6: ['6', '^'],
    Digit7: ['7', '&'],
    Digit8: ['8', '*'],
    Digit9: ['9', '('],
    Digit0: ['0', ')'],
    Minus: ['-', '_'],
    Equal: ['=', '+'],
    Backspace: ['delete'],
  },
  {
    Tab: ['tab'],
    KeyQ: ['q', 'й'],
    KeyW: ['w', 'ц'],
    KeyE: ['e', 'у'],
    KeyR: ['r', 'к'],
    KeyT: ['t', 'е'],
    KeyY: ['y', 'н'],
    KeyU: ['u', 'г'],
    KeyI: ['i', 'ш'],
    KeyO: ['o', 'щ'],
    KeyP: ['p', 'з'],
    BracketLeft: ['[', 'х'],
    BracketRight: [']', 'ъ'],
    Backslash: ['\\', 'ё'],
  },
  {
    CapsLock: ['capslock'],
    KeyA: ['a', 'ф'],
    KeyS: ['s', 'ы'],
    KeyD: ['d', 'в'],
    KeyF: ['f', 'а'],
    KeyG: ['g', 'п'],
    KeyH: ['h', 'р'],
    KeyJ: ['j', 'о'],
    KeyK: ['k', 'л'],
    KeyL: ['l', 'д'],
    Semicolon: [';', 'ж'],
    Quote: ['\'', 'э'],
    Enter: ['return'],
  },
  {
    ShiftLeft: ['shift'],
    KeyZ: ['z', 'я'],
    KeyX: ['x', 'ч'],
    KeyC: ['c', 'C'],
    KeyV: ['v', 'м'],
    KeyB: ['b', 'и'],
    KeyN: ['n', 'т'],
    KeyM: ['m', 'ь'],
    Comma: [',', 'б'],
    Period: ['.', 'ю'],
    Slash: ['/', '?'],
    ArrowUp: ['&#9650;'],
    ShiftRight: ['shift'],
  },
  {
    ControlLeft: ['control'],
    AltLeft: ['option'],
    MetaLeft: ['command'],
    Space: [' '],
    MetaRight: ['command'],
    ArrowLeft: ['&#9668;'],
    ArrowDown: ['&#9660;'],
    ArrowRight: ['&#9658;'],
    AltRight: ['option'],
  },
];

export default KEYS;
